AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloud Formation template to create SecretsManager for getting DB Connection"
Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "DbConnection"
      Description: "Connection string for MY SQL Database"
      KmsKeyId: "alias/aws/secretsmanager"
      SecretString: "{\"ConnectionString\":\"Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;\"}"
Parameters: {}
Metadata: {}
Conditions: {}